apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nexus
  labels:
    name: pvc-nexus
spec:
  storageClassName: nexus-store
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi